### PR TITLE
Optimize hyphen

### PR DESCRIPTION
**Pull request by frobinsonj**
Managed to save 15 characters here.

I am a bit confused why `((.0000001)+"")[2]` doesn't work here. It returns `"-"` in all browsers and node.js but returns `0` in tests. Any idea why?

### CODE REVIEW

**Comment by aemkei** [comment]
Hmm. That is strange. `.0000001` would be `1e-7` and `.00000001` is `1e-8`.

**Comment by hazzik** [comment]
It’s because you unwrapped the number from `+[]`.

The expressions inside the definitions are not real JavaScript expressions

**Comment by frobinsonj** [comment]
@hazzik, if that is the case, why does it work with 7 zeros and not 6? (`((.00000001)+"")[2` and not `((.0000001)+"")[2`)

Another option would be to just use `(+((+(+!+[]+[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+[!+[]+!+[]]+[+[]])+[])[+!+[]]+[+[]]+[+[]]+[+[]]+[+[]]+[+[]]+[+[]]+[+!+[]])+[])[!+[]+!+[]]` which saves a further 3 characters (18 in total)

**Comment by hazzik** [comment]
> if that is the case, why does it work with 7 zeros and not 6? (((.00000001)+"")[2] and not ((.0000001)+"")[2])

Because if there are 6 zeros the number gets converted to `0.000001`, eg it loses one `0`. With 6 zeros the number becomes `"1e-7"` (instead of `"1e-8"`).

**Comment by hazzik** [comment]
So, this works: `'(+(.+[0000001])+"")[2]'` and saves 3 characters.

**Comment by hazzik** [comment]
So, this is this: `(+(.0000001)+"")[2]`

```js
(+((+(+!+[]+[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+[!+[]+!+[]]+[+[]])+[])[+!+[]]+[]+[+[]]+[+[]]+[+[]]+[+[]]+[+[]]+[+!+[]])+[])[!+[]+!+[]]
_________________________________________________________the error is HERE ^^^^
```

And this is `(+(.0000001)+"")[2]`
```js
(+((+(+!+[]+[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+[!+[]+!+[]]+[+[]])+[])[+!+[]]+[]+[+[]]+[+[]]+[+[]]+[+[]]+[+[]]+[+[]]+[+!+[]])+[])[!+[]+!+[]]
___________________________________________________________same error HERE ^^^^
```

And this is correct version: `(+(.+[0000001])+"")[2]`
```js
(+((+(+!+[]+[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+[!+[]+!+[]]+[+[]])+[])[+!+[]]+[+[]+[+[]]+[+[]]+[+[]]+[+[]]+[+[]]+[+!+[]]])+[])[!+[]+!+[]]
______________________________________________________________no error HERE ^^^^
```

The error happens because of the double digit replacer here: https://github.com/aemkei/jsfuck/blob/977aeeff2a924a1747baf0ee34738f435fdcec05/jsfuck.js#L184

**Comment by frobinsonj** [comment]
Thanks for the explanation @hazzik :)

I will update the branch.

**Comment by frobinsonj** [comment]
@aemkei, I've updated the branch. Thanks again hazzik.

**Comment by aemkei** [comment]
Perfect. Guess we once need to add an explanation to the README about how the character mapping works.

**Pull request merged**
