### PR TITLE
Optimize long strings

### PR DESCRIPTION
**Pull request by hazzik**
The idea here goes like this: if a string has any unmapped characters it is practical to wrap the _whole_ string into an escape sequence wrapper once instead of wrapping every single unmapped character.

This way we can save around 2000 symbols (as compared to the current master) per unmapped character except first one. 

The only caveat here is that we need to escape `\` and `"`in the original string otherwise the output will be corrupt. It turns out the most efficient way to do that is to convert these characters to  escape sequences as well.

For example "XYZ" would be encoded as following:

```js
Function("return\"\\130\\131\\132\"")() // 8298 chars
```
Instead of 

```js
Function("return\"\\u0058\"")() +
Function("return\"\\u0059\"")() +
Function("return\"\\u005a\"")() // 12134 chars
```

### CODE REVIEW

**Comment by hazzik** [comment]
@aemkei I think this is ready for review.

**Comment by kamil-kielczewski** [comment]
@hazzik - this repo/project is dead? I made some changes - but I saw that your pull request is here more than year... :(

**Comment by aemkei** [comment]
Sorry but I didn't looked into this. Hope to find some time and merge the open PRs. This one is has some conflicts now with other branches.

**Comment by hazzik** [comment]
@aemkei resolved

**Review by aemkei — APPROVED** [review]

**Comment by aemkei** [comment]
Thanks for this! I was also thinking about having a simple wrapper that will put the final code into a sequence of escape sequences.

**Pull request merged**
