### PR TITLE
Fix typo & Improve example

### PR DESCRIPTION
**Pull request by zetaraku**

### CODE REVIEW

**Review by aemkei — APPROVED** [review]

**Comment by aemkei** [comment]
Thanks for the review and fixes!

**Comment by zetaraku** [comment]
I noticed that this PR was approved but closed without merge.
Is that a mistake or it will be fixed after manually :)?

**Comment by aemkei** [comment]
I am super sorry, this was a mistake!
And unfortunately I can't reopen the RP, because your repo has been deleted:
Do you still have the changes and can repost them?

**Comment by zetaraku** [comment]
I re-created the repo and restored the deleted branch but it seems that the connection has broken.
Can the PR be reopened now? If not, should I open a new PR?

**Comment by aemkei** [comment]
Looks like you have to create a new PR once the old repo was deleted.

Sorry for the trouble here.

**Pull request closed without merging**
