### PR TITLE
Optimise missing ASCII printable characters

### PR DESCRIPTION
**Pull request by frobinsonj**
Make use of ISO-8859-1 escape notation (`\XXX (where XXX is 1–3 octal digits; range of 0–377)`)

### CODE REVIEW

**Comment by hazzik** [comment]
there is one more place to use this technique (but you'll need the condition you had before):

https://github.com/aemkei/jsfuck/blob/effccc419c274f49613580357e4898bf17327e0f/jsfuck.js#L266-L273

**Comment by hazzik** [comment]
Thanks, I've borrowed your stuff into my PR #88

**Comment by frobinsonj** [comment]
> there is one more place to use this technique (but you'll need the condition you had before):
> 
> https://github.com/aemkei/jsfuck/blob/effccc419c274f49613580357e4898bf17327e0f/jsfuck.js#L265-L274

I saw that but to be honest, it was late last night and I was struggling to understand the order that everything was being called haha

Is that not just a fallback for any characters that can't already be found? I believe that all supported characters are included within `MAPPING` so it would have affect here?

**Comment by hazzik** [comment]
> Is that not just a fallback for any characters that can't already be found? 

Yes

> I believe that all supported characters are included within MAPPING so it would have no affect here?

In `MAPPING` are only characters up to ASCII code 127. So it would work for characters 128-255. Not sure how much it is helpful. I think only character which can benefit from it is `ß`

**Comment by frobinsonj** [comment]
> > Is that not just a fallback for any characters that can't already be found?
> 
> Yes
> 
> > I believe that all supported characters are included within MAPPING so it would have no affect here?
> 
> In `MAPPING` are only characters up to ASCII code 127. So this code block would work for characters 128-255. Not sure how much it is helpful. I think only character which can benefit from it is `ß`

Ah yes, of course.

Do you think it'd be worth added these to the output.txt? We should at least have a test case for some.

<details>
  <summary>There are actually quite a few characters here</summary>

DEC | OCT | HEX | BIN | Symbol | HTML Number | HTML Name | Description
-- | -- | -- | -- | -- | -- | -- | --
129 | 201 | 81 | 10000001 |   |   |   |  
141 | 215 | 8D | 10001101 |   |   |   |  
143 | 217 | 8F | 10001111 |   |   |   |  
144 | 220 | 90 | 10010000 |   |   |   |  
157 | 235 | 9D | 10011101 |   |   |   |  
160 | 240 | A0 | 10100000 |   | &#160; | &nbsp; | Non-breaking space
161 | 241 | A1 | 10100001 | ¡ | &#161; | &iexcl; | Inverted exclamation mark
162 | 242 | A2 | 10100010 | ¢ | &#162; | &cent; | Cent sign
163 | 243 | A3 | 10100011 | £ | &#163; | &pound; | Pound sign
164 | 244 | A4 | 10100100 | ¤ | &#164; | &curren; | Currency sign
165 | 245 | A5 | 10100101 | ¥ | &#165; | &yen; | Yen sign
166 | 246 | A6 | 10100110 | ¦ | &#166; | &brvbar; | Pipe, Broken vertical bar
167 | 247 | A7 | 10100111 | § | &#167; | &sect; | Section sign
168 | 250 | A8 | 10101000 | ¨ | &#168; | &uml; | Spacing diaeresis - umlaut
169 | 251 | A9 | 10101001 | © | &#169; | &copy; | Copyright sign
170 | 252 | AA | 10101010 | ª | &#170; | &ordf; | Feminine ordinal indicator
171 | 253 | AB | 10101011 | « | &#171; | &laquo; | Left double angle quotes
172 | 254 | AC | 10101100 | ¬ | &#172; | &not; | Not sign
173 | 255 | AD | 10101101 | ­ | &#173; | &shy; | Soft hyphen
174 | 256 | AE | 10101110 | ® | &#174; | &reg; | Registered trade mark sign
175 | 257 | AF | 10101111 | ¯ | &#175; | &macr; | Spacing macron - overline
176 | 260 | B0 | 10110000 | ° | &#176; | &deg; | Degree sign
177 | 261 | B1 | 10110001 | ± | &#177; | &plusmn; | Plus-or-minus sign
178 | 262 | B2 | 10110010 | ² | &#178; | &sup2; | Superscript two - squared
179 | 263 | B3 | 10110011 | ³ | &#179; | &sup3; | Superscript three - cubed
180 | 264 | B4 | 10110100 | ´ | &#180; | &acute; | Acute accent - spacing acute
181 | 265 | B5 | 10110101 | µ | &#181; | &micro; | Micro sign
182 | 266 | B6 | 10110110 | ¶ | &#182; | &para; | Pilcrow sign - paragraph sign
183 | 267 | B7 | 10110111 | · | &#183; | &middot; | Middle dot - Georgian comma
184 | 270 | B8 | 10111000 | ¸ | &#184; | &cedil; | Spacing cedilla
185 | 271 | B9 | 10111001 | ¹ | &#185; | &sup1; | Superscript one
186 | 272 | BA | 10111010 | º | &#186; | &ordm; | Masculine ordinal indicator
187 | 273 | BB | 10111011 | » | &#187; | &raquo; | Right double angle quotes
188 | 274 | BC | 10111100 | ¼ | &#188; | &frac14; | Fraction one quarter
189 | 275 | BD | 10111101 | ½ | &#189; | &frac12; | Fraction one half
190 | 276 | BE | 10111110 | ¾ | &#190; | &frac34; | Fraction three quarters
191 | 277 | BF | 10111111 | ¿ | &#191; | &iquest; | Inverted question mark
192 | 300 | C0 | 11000000 | À | &#192; | &Agrave; | Latin capital letter A with grave
193 | 301 | C1 | 11000001 | Á | &#193; | &Aacute; | Latin capital letter A with acute
194 | 302 | C2 | 11000010 | Â | &#194; | &Acirc; | Latin capital letter A with circumflex
195 | 303 | C3 | 11000011 | Ã | &#195; | &Atilde; | Latin capital letter A with tilde
196 | 304 | C4 | 11000100 | Ä | &#196; | &Auml; | Latin capital letter A with diaeresis
197 | 305 | C5 | 11000101 | Å | &#197; | &Aring; | Latin capital letter A with ring above
198 | 306 | C6 | 11000110 | Æ | &#198; | &AElig; | Latin capital letter AE
199 | 307 | C7 | 11000111 | Ç | &#199; | &Ccedil; | Latin capital letter C with cedilla
200 | 310 | C8 | 11001000 | È | &#200; | &Egrave; | Latin capital letter E with grave
201 | 311 | C9 | 11001001 | É | &#201; | &Eacute; | Latin capital letter E with acute
202 | 312 | CA | 11001010 | Ê | &#202; | &Ecirc; | Latin capital letter E with circumflex
203 | 313 | CB | 11001011 | Ë | &#203; | &Euml; | Latin capital letter E with diaeresis
204 | 314 | CC | 11001100 | Ì | &#204; | &Igrave; | Latin capital letter I with grave
205 | 315 | CD | 11001101 | Í | &#205; | &Iacute; | Latin capital letter I with acute
206 | 316 | CE | 11001110 | Î | &#206; | &Icirc; | Latin capital letter I with circumflex
207 | 317 | CF | 11001111 | Ï | &#207; | &Iuml; | Latin capital letter I with diaeresis
208 | 320 | D0 | 11010000 | Ð | &#208; | &ETH; | Latin capital letter ETH
209 | 321 | D1 | 11010001 | Ñ | &#209; | &Ntilde; | Latin capital letter N with tilde
210 | 322 | D2 | 11010010 | Ò | &#210; | &Ograve; | Latin capital letter O with grave
211 | 323 | D3 | 11010011 | Ó | &#211; | &Oacute; | Latin capital letter O with acute
212 | 324 | D4 | 11010100 | Ô | &#212; | &Ocirc; | Latin capital letter O with circumflex
213 | 325 | D5 | 11010101 | Õ | &#213; | &Otilde; | Latin capital letter O with tilde
214 | 326 | D6 | 11010110 | Ö | &#214; | &Ouml; | Latin capital letter O with diaeresis
215 | 327 | D7 | 11010111 | × | &#215; | &times; | Multiplication sign
216 | 330 | D8 | 11011000 | Ø | &#216; | &Oslash; | Latin capital letter O with slash
217 | 331 | D9 | 11011001 | Ù | &#217; | &Ugrave; | Latin capital letter U with grave
218 | 332 | DA | 11011010 | Ú | &#218; | &Uacute; | Latin capital letter U with acute
219 | 333 | DB | 11011011 | Û | &#219; | &Ucirc; | Latin capital letter U with circumflex
220 | 334 | DC | 11011100 | Ü | &#220; | &Uuml; | Latin capital letter U with diaeresis
221 | 335 | DD | 11011101 | Ý | &#221; | &Yacute; | Latin capital letter Y with acute
222 | 336 | DE | 11011110 | Þ | &#222; | &THORN; | Latin capital letter THORN
223 | 337 | DF | 11011111 | ß | &#223; | &szlig; | Latin small letter sharp s - ess-zed
224 | 340 | E0 | 11100000 | à | &#224; | &agrave; | Latin small letter a with grave
225 | 341 | E1 | 11100001 | á | &#225; | &aacute; | Latin small letter a with acute
226 | 342 | E2 | 11100010 | â | &#226; | &acirc; | Latin small letter a with circumflex
227 | 343 | E3 | 11100011 | ã | &#227; | &atilde; | Latin small letter a with tilde
228 | 344 | E4 | 11100100 | ä | &#228; | &auml; | Latin small letter a with diaeresis
229 | 345 | E5 | 11100101 | å | &#229; | &aring; | Latin small letter a with ring above
230 | 346 | E6 | 11100110 | æ | &#230; | &aelig; | Latin small letter ae
231 | 347 | E7 | 11100111 | ç | &#231; | &ccedil; | Latin small letter c with cedilla
232 | 350 | E8 | 11101000 | è | &#232; | &egrave; | Latin small letter e with grave
233 | 351 | E9 | 11101001 | é | &#233; | &eacute; | Latin small letter e with acute
234 | 352 | EA | 11101010 | ê | &#234; | &ecirc; | Latin small letter e with circumflex
235 | 353 | EB | 11101011 | ë | &#235; | &euml; | Latin small letter e with diaeresis
236 | 354 | EC | 11101100 | ì | &#236; | &igrave; | Latin small letter i with grave
237 | 355 | ED | 11101101 | í | &#237; | &iacute; | Latin small letter i with acute
238 | 356 | EE | 11101110 | î | &#238; | &icirc; | Latin small letter i with circumflex
239 | 357 | EF | 11101111 | ï | &#239; | &iuml; | Latin small letter i with diaeresis
240 | 360 | F0 | 11110000 | ð | &#240; | &eth; | Latin small letter eth
241 | 361 | F1 | 11110001 | ñ | &#241; | &ntilde; | Latin small letter n with tilde
242 | 362 | F2 | 11110010 | ò | &#242; | &ograve; | Latin small letter o with grave
243 | 363 | F3 | 11110011 | ó | &#243; | &oacute; | Latin small letter o with acute
244 | 364 | F4 | 11110100 | ô | &#244; | &ocirc; | Latin small letter o with circumflex
245 | 365 | F5 | 11110101 | õ | &#245; | &otilde; | Latin small letter o with tilde
246 | 366 | F6 | 11110110 | ö | &#246; | &ouml; | Latin small letter o with diaeresis
247 | 367 | F7 | 11110111 | ÷ | &#247; | &divide; | Division sign
248 | 370 | F8 | 11111000 | ø | &#248; | &oslash; | Latin small letter o with slash
249 | 371 | F9 | 11111001 | ù | &#249; | &ugrave; | Latin small letter u with grave
250 | 372 | FA | 11111010 | ú | &#250; | &uacute; | Latin small letter u with acute
251 | 373 | FB | 11111011 | û | &#251; | &ucirc; | Latin small letter u with circumflex
252 | 374 | FC | 11111100 | ü | &#252; | &uuml; | Latin small letter u with diaeresis
253 | 375 | FD | 11111101 | ý | &#253; | &yacute; | Latin small letter y with acute
254 | 376 | FE | 11111110 | þ | &#254; | &thorn; | Latin small letter thorn
255 | 377 | FF | 11111111 | ÿ | &#255; | &yuml; | Latin small letter y with diaeresis
</details>

**Comment by frobinsonj** [comment]
Merged PR #88 which included these changes.

**Pull request closed without merging**
