### PR TITLE
Use unicode escape sequence instead of unescape

### PR DESCRIPTION
**Pull request by hazzik**
Thanks to shorter backslash (#83) we can now use Unicode escape sequence. This shreds off around 1050 symbols from unmapped ASCI characters. Also, all remaining Unicode characters are now encoded in about 4000 symbols.

### CODE REVIEW

**Comment by hazzik** [comment]
@aemkei I have another optimization ready if you're interested: if the string contains unmapped characters, then instead of wrapping each individual character into a `Function("return ")()` it will wrap the whole string. This way it uses function wrap only once (about 2000 symbols), so the saving is 2000 per additional unmapped characters.

**Comment by aemkei** [comment]
AARg, sorry. The other PRs caused a conflict.
 Can you please check that?

**Comment by hazzik** [comment]
Resolved

**Comment by hazzik** [comment]
Please hold on merging this yet.

**Comment by aemkei** [comment]
Hmm. It says it again:

> This branch has conflicts that must be resolved.

**Comment by hazzik** [comment]
Resolved.

**Comment by aemkei** [comment]
Great work with the Unicode escapes! You are the best contributer now.

**Comment by hazzik** [comment]
Thanks

**Pull request merged**
