### PR TITLE
ES6 is current now, so use "fill" instead of "filter" to get Function constructor

### PR DESCRIPTION
**Pull request by hazzik**

### CODE REVIEW

**Comment by Zorgatone** [comment]
fill is supported only on chrome and firefox (on desktop browsers at least).

Not supported on explorer and mobile browsers

:-1:

**Comment by aemkei** [comment]
I would also keep the `filter` method, as it is working for older browsers.

**Comment by aemkei** [comment]
But many thanks for the suggestion! I love to see, that you are still trying to improve my mess.

**Comment by Zorgatone** [comment]
We could change it in the future... After people stop using old IE, and the browsers will support ES6

**Comment by hazzik** [comment]
As I see [here](https://kangax.github.io/compat-table/es6/#test-Array.prototype_methods_Array.prototype.fill) only IE (are Microsoft going to release any new versions?), some old androids, Safari and old Node.js do not support this. I think we can enable this feature soon

**Comment by aemkei** [comment]
I reopened this now, cause ES6 is now all around.

**Pull request merged**
