### PR TITLE
Optimize "b", "j", "[", "C", "U", "]"

### PR DESCRIPTION
**Pull request by hazzik**
Using "console" instead of "{}"

Works in all current browsers and node.js

Also, "C" could be optimized used `(0+Function("return console")()["constructor"])[10]`. -- need adjustment for IE using workaround from #17

### CODE REVIEW

**Comment by hazzik** [comment]
Reopen this as we do not support IE anyway /cc @subzey @aemkei

**Comment by dxa4481** [comment]
This might be a dumb question, but is there a good reason  [ ] ( ) and ! don't map to themselves?

**Comment by hazzik** [comment]
@dxa4481 it's impossible, as we need a char code/string of these characters. Without quotes they are control characters, not string literals.

**Comment by hazzik** [comment]
Superseeded by #54

**Pull request closed without merging**
